[package]
name = "wasm-bench"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
opus-decoder = { path = "../opus-decoder", default-features = false }

[features]
default = []
simd = ["opus-decoder/simd"]
neon2 = ["opus-decoder/neon2"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
